language : java

sudo: required

dist: trusty

script: mvn clean test -Dcucumber.options="--tags @sample" || travis_terminate 0
#mvn clean install

before_install:
  - - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1920x1080x24"
  - sleep 5 # give xvfb some time to start (not needed since following up command added)

jdk:
  - oraclejdk8

addons:
  chrome: stable
  firefox: latest

cache:
  directories:
    - '$HOME/.m2/repository'

env:
  global:
#    - browser= "FF"
    - DBUS_SESSION_BUS_ADDRESS= "/dev/null"

branches :
  only :
    - master
    - dev